//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int AuditoriaId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Entidad { get; set; }
        public Nullable<long> ValorKeyEntidad { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string UsuarioName { get; set; }
        public string Operacion { get; set; }
        public string ValoresAnterior { get; set; }
        public string ValoresNuevo { get; set; }
        public string MaquinaIp { get; set; }
    }
}
