//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosAdministrativos
    {
        public int DatosAdminId { get; set; }
        public Nullable<int> EstructuraId { get; set; }
        public Nullable<System.DateTime> AnioReconstruccion { get; set; }
    
        public virtual Estructuras Estructuras { get; set; }
    }
}
