//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTDetalles
    {
        public int DTDetalleId { get; set; }
        public Nullable<int> EstructuraId { get; set; }
        public Nullable<int> TipoBarandaId { get; set; }
        public Nullable<int> TipoDefensaId { get; set; }
        public Nullable<int> TipoSuperRodId { get; set; }
        public Nullable<int> TipoJuntaExpId { get; set; }
        public Nullable<int> TipoApoyoFSoporteId { get; set; }
        public Nullable<int> TipoApoyoMSoporteId { get; set; }
        public Nullable<int> TipoApoyoFVigasId { get; set; }
        public Nullable<int> TipoApoyoMVigasId { get; set; }
    
        public virtual Estructuras Estructuras { get; set; }
    }
}
