//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTGeometrias
    {
        public int DTGeometriaId { get; set; }
        public Nullable<int> EstructuraId { get; set; }
        public Nullable<double> Numeroclaros { get; set; }
        public Nullable<double> LongitudClaroMinimo { get; set; }
        public Nullable<double> LongitudClaroMaximos { get; set; }
        public Nullable<double> LongitudTotal { get; set; }
        public Nullable<double> AnchoTotal { get; set; }
        public Nullable<double> AnchoMediana { get; set; }
        public Nullable<double> AnchoAceraIzq { get; set; }
        public Nullable<double> AnchoAceraDer { get; set; }
        public Nullable<double> AnchoCalzada { get; set; }
        public Nullable<double> AnchoBordillos { get; set; }
        public Nullable<double> AnchoAcceso { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<double> CurvaTangente { get; set; }
        public Nullable<double> Esviajamiento { get; set; }
    
        public virtual Estructuras Estructuras { get; set; }
    }
}
