//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTLosa
    {
        public int DTLosaId { get; set; }
        public Nullable<int> EstructuraId { get; set; }
        public string LosaInferior { get; set; }
        public string LosaSuperior { get; set; }
        public string SeccionTrasversa { get; set; }
        public string DiseñoDeEvaluacion { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<decimal> Espesor { get; set; }
        public Nullable<int> MunicipioID { get; set; }
    
        public virtual Estructuras Estructuras { get; set; }
    }
}
