//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTMuros
    {
        public int DTMuroId { get; set; }
        public Nullable<int> EstructuraId { get; set; }
        public Nullable<int> MuroTipoId { get; set; }
        public Nullable<int> MaterialTipoId { get; set; }
        public Nullable<double> Espesor { get; set; }
        public Nullable<int> CimentacionTipoId { get; set; }
    
        public virtual Estructuras Estructuras { get; set; }
    }
}
