//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTSuperEstructuras
    {
        public int DTSuperEstrucId { get; set; }
        public Nullable<int> EstructuraId { get; set; }
        public Nullable<bool> DiseñoTipo { get; set; }
        public Nullable<int> DiseñoSeccTransvId { get; set; }
        public Nullable<int> DiseñoElevacionId { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<int> SuperEstrucClasificacionId { get; set; }
    
        public virtual Estructuras Estructuras { get; set; }
    }
}
