//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstructuraDetalles
    {
        public int EstructuraDetalleId { get; set; }
        public Nullable<int> EstructuraId { get; set; }
        public Nullable<bool> PasoCauce { get; set; }
        public Nullable<bool> Desviacion { get; set; }
        public Nullable<int> LongitudRutaDir { get; set; }
        public Nullable<bool> DesviacionPavim { get; set; }
        public Nullable<int> DesviacionEstSeca { get; set; }
        public Nullable<int> DesviacionEstLluvia { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Estructuras Estructuras { get; set; }
    }
}
