//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspecciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspecciones()
        {
            this.InspeccionComponentes = new HashSet<InspeccionComponentes>();
        }
    
        public int InspeccionId { get; set; }
        public Nullable<int> EstructuraId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> TipoInspeccionId { get; set; }
        public Nullable<System.DateTime> AnioProxInsp { get; set; }
        public Nullable<int> TransitoTPDA { get; set; }
        public Nullable<int> EstacionConteo { get; set; }
        public Nullable<double> VehLivianos { get; set; }
        public Nullable<double> VehPesados { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Estructuras Estructuras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspeccionComponentes> InspeccionComponentes { get; set; }
    }
}
