//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspeccionComponentes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspeccionComponentes()
        {
            this.InspeccionComponenteFotos = new HashSet<InspeccionComponenteFotos>();
            this.TrabajosEstandar = new HashSet<TrabajosEstandar>();
        }
    
        public int InspeccionComponenteId { get; set; }
        public Nullable<int> InspeccionId { get; set; }
        public Nullable<int> ComponenteId { get; set; }
        public string Calificacion { get; set; }
        public Nullable<int> Mantenimiento { get; set; }
        public Nullable<int> InspeccionEspecial { get; set; }
        public Nullable<int> NumFotos { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> TipoDañoId { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<double> Costo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspeccionComponenteFotos> InspeccionComponenteFotos { get; set; }
        public virtual Inspecciones Inspecciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajosEstandar> TrabajosEstandar { get; set; }
    }
}
