//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miscelaneas
    {
        public int MiscelaneaId { get; set; }
        public Nullable<int> EstructuraId { get; set; }
        public Nullable<int> RespInspeccionId { get; set; }
        public Nullable<int> ProyectistaId { get; set; }
        public Nullable<double> LatitudG { get; set; }
        public Nullable<double> LatitudM { get; set; }
        public Nullable<double> LatitudS { get; set; }
        public Nullable<double> LongitudG { get; set; }
        public Nullable<double> LongitudM { get; set; }
        public Nullable<double> LongitudS { get; set; }
        public Nullable<double> Altitud { get; set; }
        public Nullable<int> TipoInstalacionesId { get; set; }
    
        public virtual Estructuras Estructuras { get; set; }
    }
}
