//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablausuario
    {
        public int Id { get; set; }
        public Nullable<int> Idrol { get; set; }
        public string nombres { get; set; }
        public string apellido { get; set; }
        public string Usuario { get; set; }
        public string password { get; set; }
    }
}
