//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tramos
    {
        public int TramoId { get; set; }
        public Nullable<int> EstructuraId { get; set; }
        public Nullable<int> NumPaso { get; set; }
        public Nullable<int> TipoPasoId { get; set; }
        public Nullable<bool> PasoPrimero { get; set; }
        public Nullable<bool> Paso { get; set; }
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Lado { get; set; }
        public Nullable<double> PMSkm { get; set; }
        public Nullable<double> PMSm { get; set; }
        public Nullable<double> PKMkm { get; set; }
        public Nullable<double> PKMm { get; set; }
        public string CargaDiseño { get; set; }
        public Nullable<int> ClaseDistribCargaId { get; set; }
        public Nullable<int> NormaDiseñoId { get; set; }
        public Nullable<double> GaliboVerticalI { get; set; }
        public Nullable<double> GaliboVerticalIM { get; set; }
        public Nullable<double> GaliboVerticalDM { get; set; }
        public Nullable<double> GaliboVerticalD { get; set; }
        public Nullable<double> ClasePuente { get; set; }
        public Nullable<bool> Restringido { get; set; }
        public Nullable<double> CargaEjeMaxima { get; set; }
        public Nullable<int> ConsultorId { get; set; }
        public Nullable<System.DateTime> FechaCapacidad { get; set; }
    
        public virtual Estructuras Estructuras { get; set; }
    }
}
